require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/sent_players", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # SentPlayer. As you add validations to SentPlayer, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # SentPlayersController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "GET /index" do
    it "renders a successful response" do
      SentPlayer.create! valid_attributes
      get sent_players_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      sent_player = SentPlayer.create! valid_attributes
      get sent_player_url(sent_player), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SentPlayer" do
        expect {
          post sent_players_url,
               params: { sent_player: valid_attributes }, headers: valid_headers, as: :json
        }.to change(SentPlayer, :count).by(1)
      end

      it "renders a JSON response with the new sent_player" do
        post sent_players_url,
             params: { sent_player: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SentPlayer" do
        expect {
          post sent_players_url,
               params: { sent_player: invalid_attributes }, as: :json
        }.to change(SentPlayer, :count).by(0)
      end

      it "renders a JSON response with errors for the new sent_player" do
        post sent_players_url,
             params: { sent_player: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json")
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested sent_player" do
        sent_player = SentPlayer.create! valid_attributes
        patch sent_player_url(sent_player),
              params: { sent_player: new_attributes }, headers: valid_headers, as: :json
        sent_player.reload
        skip("Add assertions for updated state")
      end

      it "renders a JSON response with the sent_player" do
        sent_player = SentPlayer.create! valid_attributes
        patch sent_player_url(sent_player),
              params: { sent_player: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the sent_player" do
        sent_player = SentPlayer.create! valid_attributes
        patch sent_player_url(sent_player),
              params: { sent_player: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json")
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested sent_player" do
      sent_player = SentPlayer.create! valid_attributes
      expect {
        delete sent_player_url(sent_player), headers: valid_headers, as: :json
      }.to change(SentPlayer, :count).by(-1)
    end
  end
end
